name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (if needed)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t qr-backend:ci ./backend

      - name: Run container
        run: |
          docker run -d --name qr-backend -p 8000:8000 --env-file ./backend/.env qr-backend:ci
          sleep 5  # wait for app to start

      - name: Run smoke test
        run: |
          curl -f http://localhost:8000/api/v1/utils/qr?data=Test -o /dev/null
          echo 'Smoke test passed'
